"""API key management for Agent Catalogue.

Stores API keys in ~/.agent-catalogue/keys.env (chmod 600).
Keys are loaded into os.environ on startup, but env vars take precedence
over stored keys (so CI/CD overrides work naturally).

Settings.yaml uses ${VAR_NAME} placeholders that resolve to these keys at runtime.
"""

from __future__ import annotations

import logging
import os
import platform
import stat
from pathlib import Path

from agent_catalogue.paths import get_keys_path

logger = logging.getLogger(__name__)

HEADER = """# Agent Catalogue API Keys
# Auto-generated by: agent-catalogue init
# These are loaded automatically on startup.
# Environment variables take precedence over values stored here.
"""


class KeyManager:
    """Manages API key storage in keys.env."""

    def __init__(self, keys_path: Path | None = None) -> None:
        self._path = keys_path or get_keys_path()
        self._loaded = False

    def load_keys(self) -> None:
        """Load keys from keys.env into os.environ.

        Only sets keys that are NOT already in the environment,
        so explicit env vars (e.g., from CI) always win.
        """
        if self._loaded:
            return
        self._loaded = True

        if not self._path.exists():
            return

        try:
            for key, value in self._parse_env_file().items():
                if key not in os.environ or not os.environ[key]:
                    os.environ[key] = value
                    logger.debug("Loaded key %s from keys.env", key)
        except Exception:
            logger.debug("Failed to load keys.env", exc_info=True)

    def save_key(self, key_name: str, value: str) -> None:
        """Save or update a key in keys.env and set it in os.environ."""
        self._path.parent.mkdir(parents=True, exist_ok=True)

        # Read existing keys
        existing = self._parse_env_file() if self._path.exists() else {}

        # Update
        existing[key_name] = value

        # Write back
        lines = [HEADER]
        for k, v in sorted(existing.items()):
            lines.append(f'{k}="{v}"')
        self._path.write_text("\n".join(lines) + "\n", encoding="utf-8")

        # Set permissions (not on Windows)
        if platform.system() != "Windows":
            self._path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600

        # Also set in current process
        os.environ[key_name] = value
        logger.debug("Saved key %s to keys.env", key_name)

    def get_key(self, key_name: str) -> str | None:
        """Get a key value. Checks env first, then keys.env."""
        env_val = os.environ.get(key_name)
        if env_val:
            return env_val

        if self._path.exists():
            keys = self._parse_env_file()
            return keys.get(key_name)

        return None

    def has_key(self, key_name: str) -> bool:
        """Check if a key is available (env or keys.env)."""
        return bool(self.get_key(key_name))

    def _parse_env_file(self) -> dict[str, str]:
        """Parse keys.env file into key-value dict."""
        result: dict[str, str] = {}
        if not self._path.exists():
            return result

        for line in self._path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key:
                result[key] = value

        return result
